# Generated by Django 4.1.1 on 2022-09-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBase', '0002_customuser_first_name_customuser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.TextField(max_length=40),
        ),
    ]
